### ISSUE TITLE
Get 3.x Release Into Central

### ISSUE THREAD

**Issue by scinnamond** [teetime-framework/TeeTime#2]
I "tweeted" about this. Just adding an issue here as well.

**Comment by ChristianWulf** [comment]
Thanks for your hint. Which feature from our 3.0 snapshot version is important to you?

**Comment by scinnamond** [comment]
Christian; I'm using multiple initial producer stages with a merger. The
multiple initial stages is the only thing I found for sure not to be in the
latest 2.x version on Central.

**Comment by ChristianWulf** [comment]
I think I do not get your point. I have successfully tested the following minimal example with TeeTime 2.1:
```java
public class MutipleInitialStagesConfig extends Configuration {

	public MutipleInitialStagesConfig(List<Integer> resultingElements) {
		InitialElementProducer<Integer> producer0 = new InitialElementProducer<>(1, 2, 3);
		InitialElementProducer<Integer> producer1 = new InitialElementProducer<>(4, 5, 6);
		InitialElementProducer<Integer> producer2 = new InitialElementProducer<>(7, 8, 9);
		Merger<Integer> merger = new Merger<>();
		CollectorSink<Integer> sink = new CollectorSink<>(resultingElements);

		connectPorts(producer0.getOutputPort(), merger.getNewInputPort());
		connectPorts(producer1.getOutputPort(), merger.getNewInputPort());
		connectPorts(producer2.getOutputPort(), merger.getNewInputPort());
		connectPorts(merger.getOutputPort(), sink.getInputPort());

		merger.declareActive();
	}

	public static void main(String[] args) {
		List<Integer> resultingElements = new ArrayList<>();
		MutipleInitialStagesConfig config = new MutipleInitialStagesConfig(resultingElements);
		new Execution<>(config).executeBlocking();

		System.out.println("elements: "+resultingElements);
	}
}
```
I got `elements: [7, 1, 4, 8, 2, 5, 9, 3, 6]`

**Comment by scinnamond** [comment]
Calling merger.declareActive() AFTER all stages are connected, like your
example,  did the trick for my 2.x problem. So thanks I can stick with 2.x
for now. --Scott

**Comment by ChristianWulf** [comment]
Great! Just for your information: with TeeTime 3.0, which we will release in a few weeks, we do not require any ordering anymore.
